# Generated by Django 5.0.3 on 2025-12-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR')], default='eur', max_length=3),
        ),
    ]
